const {
  Client,
  GatewayIntentBits,
  EmbedBuilder,
  ActionRowBuilder,
  StringSelectMenuBuilder,
  ButtonBuilder,
  ButtonStyle,
  PermissionFlagsBits,
  ChannelType,
  PermissionsBitField
} = require('discord.js');
const fs = require('fs');
const http = require('http');

const PREFIX = 'p.';
const DATA_FILE = './economy.json';
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildPresences] });

if (!fs.existsSync(DATA_FILE)) fs.writeFileSync(DATA_FILE, '{}');
let economy = {};
try { economy = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')); } catch { economy = {}; fs.writeFileSync(DATA_FILE, '{}'); }
if (!economy || typeof economy !== 'object' || Array.isArray(economy)) economy = {};
function save() { try { fs.writeFileSync(DATA_FILE, JSON.stringify(economy, null, 2)); } catch (e) { console.error('❌ Error guardando datos:', e); } }

function getUser(id) {
  if (!economy[id] || typeof economy[id] !== 'object' || Array.isArray(economy[id])) economy[id] = { cash: 1000, bank: 0, wins: 0, losses: 0, messages: 0, commands: 0, daily: 0, work: 0, crime: 0, robWins: 0, robLosses: 0, inventory: {}, warnings: [], xp: 0, achievements: [], streak: 0, lastDaily: 0, reminders: [] };
  const u = economy[id];
  for (const k of ['cash','bank','wins','losses','messages','commands','daily','work','crime','robWins','robLosses','xp','streak','lastDaily']) u[k] = Number(u[k]) || 0;
  if (!u.inventory || typeof u.inventory !== 'object' || Array.isArray(u.inventory)) u.inventory = {};
  if (!Array.isArray(u.warnings)) u.warnings = [];
  if (!Array.isArray(u.achievements)) u.achievements = [];
  if (!Array.isArray(u.reminders)) u.reminders = [];
  return u;
}
function getGuildConfig(id) {
  if (!economy[id] || typeof economy[id] !== 'object' || Array.isArray(economy[id])) economy[id] = { welcomeChannel: null, autoRoles: [], autoReplies: {}, autoReactions: {}, rankActive: false, ticketCategory: null, ticketLog: null, ticketStaffRole: null, ticketCounter: 0, autoMessages: [] };
  const c = economy[id];
  if (!('welcomeChannel' in c)) c.welcomeChannel = null;
  if (!Array.isArray(c.autoRoles)) c.autoRoles = c.autoRole ? [c.autoRole] : [];
  if (!c.autoReplies || typeof c.autoReplies !== 'object') c.autoReplies = {};
  if (!c.autoReactions || typeof c.autoReactions !== 'object') c.autoReactions = {};
  if (typeof c.rankActive !== 'boolean') c.rankActive = false;
  if (!('ticketCategory' in c)) c.ticketCategory = null;
  if (!('ticketLog' in c)) c.ticketLog = null;
  if (!('ticketStaffRole' in c)) c.ticketStaffRole = null;
  if (!Number.isInteger(c.ticketCounter)) c.ticketCounter = 0;
  if (!Array.isArray(c.autoMessages)) c.autoMessages = [];
  return c;
}
const money = v => Number(v || 0).toLocaleString('es-ES');
const random = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const embed = (color, title, text, footer = 'Joshua 🤖 • Sistema oficial') => new EmbedBuilder().setColor(color).setTitle(title).setDescription(text).setFooter({ text: footer }).setTimestamp();
const ok = t => embed(0x57F287, '╭━━━〔 ✅ JOSHUA 〕━━━╮', t, 'Joshua 🤖 • Acción completada ✨');
const fail = t => embed(0xED4245, '╭━━━〔 ❌ JOSHUA 〕━━━╮', t, 'Joshua 🤖 • Revisa los datos ⚠️');
const info = t => embed(0x5865F2, '╭━━━〔 🤖 JOSHUA 〕━━━╮', t);
const isAdmin = m => Boolean(m.member?.permissions?.has(PermissionFlagsBits.Administrator));
const cooldowns = new Map();
function cooldown(id, cmd, seconds) { const key = `${id}:${cmd}`, now = Date.now(), remaining = seconds * 1000 - (now - (cooldowns.get(key) || 0)); if (remaining > 0) return remaining; cooldowns.set(key, now); return 0; }
function left(ms) { const s = Math.ceil(ms / 1000); return s >= 3600 ? `${Math.floor(s / 3600)}h` : s >= 60 ? `${Math.floor(s / 60)}m` : `${s}s`; }
function rankData(id) { const u = getUser(id), total = u.cash + u.bank, xp = Math.floor(u.messages * 2 + u.commands * 3 + total / 20 + u.xp); return { total, xp, level: Math.floor(xp / 100) + 1 }; }
function leaderboard(guild) { return [...guild.members.cache.values()].filter(m => !m.user.bot).map(member => ({ member, ...rankData(member.id) })).sort((a, b) => b.xp - a.xp); }
const shopItems = { cookie: { name: '🍪 Galleta', price: 100 }, pizza: { name: '🍕 Pizza', price: 500 }, diamond: { name: '💎 Diamante', price: 2500 }, crown: { name: '👑 Corona', price: 5000 }, gaming: { name: '🎮 Consola Gaming', price: 7500 }, trophy: { name: '🏆 Trofeo', price: 10000 }, ticket: { name: '🎟️ Ticket dorado', price: 15000 }, crystal: { name: '🔮 Cristal mágico', price: 25000 } };
const categories = { economy: ['balance','bank','daily','work','crimen','hut','robar','bonus','dep','with','pay','gift','give','topmoney'], shop: ['shop','buy','inventory','sell'], profile: ['profile','stats','userinfo','whois','avatar','rank','logros'], fun: ['coinflip','dado','random','choose','8ball','rps','reverse','joke','rate','quiz','math'], social: ['highfive','compliment','friend','wave','hug','ship','encuesta'], server: ['serverinfo','servericon','channels','roles','emojis','boosts','membercount','serverowner','serverid'], utility: ['help','ping','uptime','botinfo','time','convertir','reminder','poll','say'], admin: ['ban','unban','kick','warn','warns','purge','lock','unlock','slowmode','nick','addrole','removerole','mute','unmute'], automation: ['bienvenidas','autorroles','autorespuestas','autoreacciones'], rank: ['rank','nivel','xp','topxp'], tickets: ['ticket','ticket config','ticket close','ticket claim','ticket add','ticket remove','ticket rename','ticket transcript'], achievements: ['logros','nivel','xp','racha'] };
function help(category = 'main') { const names = { economy: ['Economía','💰'], shop: ['Tienda','🛒'], profile: ['Perfil','👤'], fun: ['Juegos','🎮'], social: ['Social','👥'], server: ['Servidor','🏰'], utility: ['Utilidades','⚙️'], admin: ['Moderación','🛡️'], automation: ['Automatización','🤖'], rank: ['Rank','🏆'], tickets: ['Tickets','🎫'], achievements: ['Logros','🏅'] }; const text = category === 'main' ? '╭───────────────╮\n     🤖 **JOSHUA**\n╰───────────────╯\n\n' + Object.values(names).map(x => `${x[1]} ${x[0]}`).join('\n') + '\n\n📌 Selecciona una categoría.' : `✨ **Comandos de ${names[category]?.[0] || category}**\n\n${(categories[category] || []).map(x => `🔹 **${PREFIX}${x}**`).join('\n')}`; return embed(0x5865F2, `╭━━━〔 📚 ${category === 'main' ? 'CENTRO DE AYUDA' : category.toUpperCase()} 〕━━━╮`, text, 'Joshua 🤖 • Centro de comandos'); }
function helpMenu() { const names = { economy: ['Economía','💰'], shop: ['Tienda','🛒'], profile: ['Perfil','👤'], fun: ['Juegos','🎮'], social: ['Social','👥'], server: ['Servidor','🏰'], utility: ['Utilidades','⚙️'], admin: ['Moderación','🛡️'], automation: ['Automatización','🤖'], rank: ['Rank','🏆'], tickets: ['Tickets','🎫'], achievements: ['Logros','🏅'] }; return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('joshua_help').setPlaceholder('📚 Selecciona una categoría').addOptions(Object.entries(names).map(([value, [label, emoji]]) => ({ label, value, emoji })))); }
const hutQuestions = [['math','🧮 ¿Cuánto es 17 × 8 + 6?', ['142']], ['riddle','🧠 Tengo agujas y no sé coser. ¿Qué soy?', ['reloj','un reloj']], ['logic','🧠 ¿Qué número sigue: 2, 4, 8, 16, ...?', ['32']], ['riddle','🧠 Tiene dientes pero no muerde. ¿Qué es?', ['peine','un peine']]];
const activeHut = new Map();
const normalizeAnswer = s => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().replace(/[^a-z0-9 ]/g, '');

client.on('guildMemberAdd', async member => { try { const c = getGuildConfig(member.guild.id); for (const id of c.autoRoles) { const r = member.guild.roles.cache.get(id); if (r && !r.managed && r.editable) await member.roles.add(r, 'Autorol de Joshua').catch(() => {}); } if (c.welcomeChannel) { const ch = member.guild.channels.cache.get(c.welcomeChannel); if (ch?.isTextBased()) await ch.send({ content: `👋 ¡Bienvenido/a ${member}! 🎉`, embeds: [embed(0x5865F2, '╭━━━〔 👑 ¡NUEVO MIEMBRO! 〕━━━╮', `✨ **¡BIENVENIDO/A!** ✨\n\n👋 ¡Qué alegría recibirte, ${member}!\n\n👤 **Jugador:** ${member.user.username}\n🏰 **Servidor:** ${member.guild.name}\n\n📜 Lee las reglas y usa **p.help** para descubrir Joshua.`)], allowedMentions: { users: [member.id] } }); } save(); } catch (e) { console.error('❌ Error bienvenida:', e); } });

client.on('messageCreate', async message => {
  try {
    if (message.author.bot || !message.guild) return;
    const user = getUser(message.author.id); user.messages++;
    const raw = message.content.trim(), content = raw.toLowerCase(), config = getGuildConfig(message.guild.id); save();
    for (const [id, h] of activeHut) if (h.author === message.author.id && h.channel === message.channel.id && raw) { activeHut.delete(id); const good = h.answers.map(normalizeAnswer).includes(normalizeAnswer(raw)); if (good) { const amount = random(500, 750); user.cash += amount; user.wins++; save(); return message.reply({ embeds: [ok(`🧠 **¡RESPUESTA CORRECTA!**\n\n💰 Ganaste **${money(amount)} 🪙**`)], allowedMentions: { repliedUser: false } }); } const loss = Math.min(800, user.cash); user.cash -= loss; user.losses++; save(); return message.reply({ embeds: [fail(`🧠 **RESPUESTA INCORRECTA**\n\n💸 Perdiste **${money(loss)} 🪙**.`)], allowedMentions: { repliedUser: false } }); }
    if (!content.startsWith(PREFIX)) { for (const [t, r] of Object.entries(config.autoReplies)) if (content === t.toLowerCase()) await message.reply({ content: r, allowedMentions: { repliedUser: false } }); for (const [t, e] of Object.entries(config.autoReactions)) if (content === t.toLowerCase()) await message.react(e).catch(() => {}); if (content.includes('hola joshua')) return message.reply('👋 ¡Holaaa! Soy Joshua 🤖✨'); if (content === 'buenas') return message.reply('😎 ¡Buenas! ¿Qué tal? 🔥'); if (content.includes('joshua god') || content.includes('joshua goat')) return message.react('🔥').catch(() => {}); return; }
    const args = raw.slice(PREFIX.length).trim().split(/\s+/).filter(Boolean), command = (args.shift() || '').toLowerCase(); if (!command) return; user.commands++; save(); const reply = p => message.reply(typeof p === 'string' ? { content: p, allowedMentions: { repliedUser: false } } : { ...p, allowedMentions: { repliedUser: false } });
    if (command === 'help' || command === 'ayuda') return reply({ embeds: [help(categories[args.join(' ').toLowerCase()] ? args.join(' ').toLowerCase() : 'main')], components: [helpMenu()] });
    if (command === 'ping') return reply({ embeds: [info(`🏓 **Ping:** ${client.ws.ping}ms\n🟢 **Estado:** Conectado`)] });
    if (['balance','bal','bank'].includes(command)) return reply({ embeds: [info(`💵 **Efectivo:** ${money(user.cash)} 🪙\n🏦 **Banco:** ${money(user.bank)} 🪙\n💎 **Patrimonio:** ${money(user.cash + user.bank)} 🪙`)] });
    if (['daily','work','crimen'].includes(command)) { const cd = cooldown(message.author.id, command, { daily: 86400, work: 30, crimen: 120 }[command]); if (cd) return reply({ embeds: [fail(`⏰ Espera **${left(cd)}**.`)] }); if (command === 'daily') { const amount = random(900, 1300); user.cash += amount; user.daily++; user.wins++; user.streak++; user.lastDaily = Date.now(); save(); return reply({ embeds: [ok(`🎁 **RECOMPENSA DIARIA**\n\n💰 Recibiste **${money(amount)} 🪙**\n🔥 Racha: **${user.streak} días**`)] }); } if (command === 'work') { const amount = random(10, 150); user.cash += amount; user.work++; user.wins++; save(); return reply({ embeds: [ok(`💼 Ganaste **${money(amount)} 🪙**.`)] }); } if (Math.random() < .2) { const amount = random(300, 500); user.cash += amount; user.crime++; user.wins++; save(); return reply({ embeds: [ok(`🕵️ Crimen ficticio exitoso. Ganaste **${money(amount)} 🪙**.`)] }); } const amount = Math.min(user.cash, random(200, 600)); user.cash -= amount; user.crime++; user.losses++; save(); return reply({ embeds: [fail(`🚔 Crimen fallido. Perdiste **${money(amount)} 🪙**.`)] }); }
    if (command === 'hut') { const cd = cooldown(message.author.id, 'hut', 180); if (cd) return reply({ embeds: [fail(`🧠 HUT en cooldown. Espera **${left(cd)}**.`)] }); const q = hutQuestions[random(0, hutQuestions.length - 1)], id = `${message.author.id}:${Date.now()}`; activeHut.set(id, { author: message.author.id, answers: q[2], channel: message.channel.id }); setTimeout(() => activeHut.delete(id), 20000); return reply({ embeds: [embed(0x9B59B6, '╭━━━〔 🧠 HUT • RETO ECONÓMICO 〕━━━╮', `🎯 **${q[1]}**\n\n⏳ Tienes **20 segundos**.\n💰 Premio: **500 a 750 🪙**\n💸 Fallo: **-800 🪙**`)] }); }
    if (['dep','deposit','with','withdraw'].includes(command)) { const withdraw = ['with','withdraw'].includes(command), arg = (args[0] || '').toLowerCase(), amount = arg === 'all' ? (withdraw ? user.bank : user.cash) : Number(arg), source = withdraw ? user.bank : user.cash; if (!Number.isSafeInteger(amount) || amount <= 0 || amount > source) return reply({ embeds: [fail(`💸 Cantidad inválida. Usa **p.${command} cantidad** o **all**.`)] }); if (withdraw) { user.bank -= amount; user.cash += amount; } else { user.cash -= amount; user.bank += amount; } save(); return reply({ embeds: [ok(`${withdraw ? '📤 Retiraste' : '📥 Depositaste'} **${money(amount)} 🪙**.`)] }); }
    if (['pay','gift','give'].includes(command)) { const target = message.mentions.users.first(), amount = Number(args.find(x => /^\d+$/.test(x))); if (!target || target.bot || target.id === message.author.id || !Number.isSafeInteger(amount) || amount <= 0 || user.cash < amount) return reply({ embeds: [fail(`Uso: **p.${command} @usuario cantidad**`)] }); user.cash -= amount; getUser(target.id).cash += amount; save(); return reply({ embeds: [ok(`🎁 Enviaste **${money(amount)} 🪙** a ${target}.`)] }); }
    if (['robar','rob'].includes(command)) { const target = message.mentions.users.first(); if (!target || target.bot || target.id === message.author.id) return reply({ embeds: [fail('🕵️ Menciona a otro usuario válido.')] }); const cd = cooldown(message.author.id, 'robar', 120); if (cd) return reply({ embeds: [fail(`⏰ Espera **${left(cd)}**.`)] }); const victim = getUser(target.id); if (victim.cash < 100) return reply({ embeds: [fail('💸 Ese usuario no tiene suficiente efectivo virtual.')] }); if (Math.random() < .5) { const amount = random(50, Math.min(victim.cash, 500)); victim.cash -= amount; user.cash += amount; user.robWins++; save(); return reply({ embeds: [ok(`🕵️ ¡Robo exitoso! Conseguíste **${money(amount)} 🪙** de ${target}.`)] }); } const fine = Math.min(user.cash, random(25, 150)); user.cash -= fine; user.robLosses++; save(); return reply({ embeds: [fail(`🚨 ¡Te atraparon! Perdiste **${money(fine)} 🪙**.`)] }); }
    if (command === 'bonus') { const cd = cooldown(message.author.id, 'bonus', 43200); if (cd) return reply({ embeds: [fail(`⏰ Espera **${left(cd)}**.`)] }); const amount = random(100, 500); user.cash += amount; save(); return reply({ embeds: [ok(`🎁 BONUS ESPECIAL: recibiste **${money(amount)} 🪙**.`)] }); }
    if (['top','leaderboard','topmoney'].includes(command)) { const members = await message.guild.members.fetch().catch(() => message.guild.members.cache); const list = [...members.values()].filter(m => !m.user.bot).map(m => ({ m, total: getUser(m.id).cash + getUser(m.id).bank })).sort((a,b) => b.total - a.total).slice(0,10); return reply({ embeds: [embed(0xF1C40F, '╭━━━〔 🏆 TOP DINERO 〕━━━╮', list.map((x,i) => `**${i+1}.** ${x.m.user.username} • **${money(x.total)} 🪙**`).join('\n') || 'Sin datos.')] }); }
    if (['shop','tienda'].includes(command)) return reply({ embeds: [embed(0xFEE75C, '╭━━━〔 🛒 TIENDA DE JOSHUA 〕━━━╮', Object.entries(shopItems).map(([id,x]) => `🛍️ **${id}** — ${x.name} • **${money(x.price)} 🪙**`).join('\n\n'))] });
    if (['buy','comprar'].includes(command)) { const id = (args[0] || '').toLowerCase(), q = Math.max(1, Number(args[1]) || 1), item = shopItems[id], total = item?.price * q; if (!item || !Number.isSafeInteger(q) || q > 100 || user.cash < total) return reply({ embeds: [fail('❌ Objeto, cantidad o saldo inválido. Usa **p.shop**.')] }); user.cash -= total; user.inventory[id] = (user.inventory[id] || 0) + q; save(); return reply({ embeds: [ok(`🛒 Compraste **${q}x ${item.name}** por **${money(total)} 🪙**.`)] }); }
    if (['inventory','inv'].includes(command)) return reply({ embeds: [info(Object.entries(user.inventory).filter(([,v]) => v > 0).map(([id,v]) => `${shopItems[id]?.name || id}: **${v}**`).join('\n') || '🎒 Tu inventario está vacío.')] });
    if (['sell','vender'].includes(command)) { const id = (args[0] || '').toLowerCase(), q = Math.max(1, Number(args[1]) || 1), item = shopItems[id]; if (!item || !Number.isSafeInteger(q) || (user.inventory[id] || 0) < q) return reply({ embeds: [fail('❌ Objeto o cantidad inválida.')] }); const total = Math.floor(item.price * q / 2); user.inventory[id] -= q; user.cash += total; save(); return reply({ embeds: [ok(`💰 Vendiste **${q}x ${item.name}** y recibiste **${money(total)} 🪙**.`)] }); }
    if (['coinflip','flip'].includes(command)) return reply({ embeds: [info(`🪙 **Moneda:** ${Math.random() < .5 ? 'Cara' : 'Cruz'}`)] });
    if (['dado','dice'].includes(command)) return reply({ embeds: [info(`🎲 **Resultado:** ${random(1,6)}`)] });
    if (command === 'random') { const a = Number(args[0]) || 1, b = Number(args[1]) || 100; if (!Number.isFinite(a) || !Number.isFinite(b) || a > b) return reply({ embeds: [fail('❌ Usa **p.random 1 100**.')] }); return reply({ embeds: [info(`🎲 Número aleatorio: **${random(a,b)}**`)] }); }
    if (command === 'choose') return args.length > 1 ? reply({ embeds: [info(`🤔 Joshua eligió: **${args[random(0,args.length-1)]}**`)] }) : reply({ embeds: [fail('❌ Usa **p.choose opción1 opción2**.')] });
    if (command === '8ball') return reply({ embeds: [info(`🎱 ${['🟢 Sí.','🔴 No.','🟡 Tal vez.','✨ Probablemente.','🤔 No estoy seguro.','🔥 Definitivamente.'][random(0,5)]}`)] });
    if (command === 'joke') return reply({ embeds: [info(['😂 ¿Qué hace una abeja en el gimnasio? ¡Zum-ba!','🤣 ¿Qué le dijo un cero a un ocho? ¡Bonito cinturón!','😎 ¿Qué hace un pez? ¡Nada!'][random(0,2)])] });
    if (command === 'reverse') return args.length ? reply({ embeds: [info(`🔄 ${args.join(' ').split('').reverse().join('')}`)] }) : reply({ embeds: [fail('❌ Usa **p.reverse texto**.')] });
    if (command === 'rate') return args.length ? reply({ embeds: [info(`📊 Joshua le da a **${args.join(' ')}** un **${random(0,100)}%**.`)] }) : reply({ embeds: [fail('❌ Usa **p.rate algo**.')] });
    if (command === 'rps') { const c = ['piedra','papel','tijera'], p = (args[0] || '').toLowerCase(), b = c[random(0,2)]; if (!c.includes(p)) return reply({ embeds: [fail('❌ Usa piedra, papel o tijera.')] }); const win = p === 'piedra' && b === 'tijera' || p === 'papel' && b === 'piedra' || p === 'tijera' && b === 'papel'; return reply({ embeds: [info(`🎮 Tú: **${p}**\n🤖 Joshua: **${b}**\n\n${p === b ? '🤝 Empate' : win ? '🎉 ¡Ganaste!' : '😅 ¡Perdiste!'}`)] }); }
    if (command === 'ship') { const u = [...message.mentions.users.values()].slice(0,2); return u.length < 2 ? reply({ embeds: [fail('❌ Menciona a dos usuarios.')] }) : reply({ embeds: [info(`💞 ${u[0]} + ${u[1]}\n\n❤️ Compatibilidad ficticia: **${random(0,100)}%**`)] }); }
    if (['highfive','hug','pat','wave','saludar','compliment'].includes(command)) { const t = message.mentions.users.first(); if (!t) return reply({ embeds: [fail('❌ Menciona a alguien.')] }); return reply({ embeds: [ok(`${message.author} ${command === 'compliment' ? '✨ ¡Eres genial!' : `${command} a ${t}! ✨`}`)] }); }
    if (['serverinfo','servericon','channels','roles','emojis','boosts','membercount','serverowner','serverid','banners'].includes(command)) { const g = message.guild; if (command === 'servericon') return g.iconURL() ? reply({ embeds: [new EmbedBuilder().setColor(0x5865F2).setTitle('🖼️ ICONO').setImage(g.iconURL({ size: 1024 }))] }) : reply({ embeds: [fail('❌ El servidor no tiene icono.')] }); if (command === 'membercount') return reply({ embeds: [info(`👥 Miembros: **${g.memberCount}**`)] }); return reply({ embeds: [info(`🏰 **${g.name}**\n👥 Miembros: **${g.memberCount}**\n💬 Canales: **${g.channels.cache.size}**\n🎭 Roles: **${g.roles.cache.size}**\n🚀 Boosts: **${g.premiumSubscriptionCount || 0}**\n🆔 ID: **${g.id}**`)] }); }
    if (command === 'uptime') { const s = Math.floor(process.uptime()); return reply({ embeds: [info(`⏱️ **Uptime:** ${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m ${s%60}s`)] }); }
    if (command === 'botinfo') return reply({ embeds: [info(`🤖 **JOSHUA**\n\n📚 Prefijo: **p.**\n⚡ Ping: **${client.ws.ping}ms**\n🏰 Servidores: **${client.guilds.cache.size}**`)] });
    if (['rank','nivel','xp'].includes(command)) { if (!config.rankActive && !isAdmin(message)) return reply({ embeds: [fail('🏆 El Rank aún no está activado.')] }); const d = rankData(message.mentions.users.first()?.id || message.author.id); return reply({ embeds: [embed(0xF1C40F, '╭━━━〔 🏆 RANK 〕━━━╮', `⭐ Nivel: **${d.level}**\n✨ XP: **${d.xp}**\n💰 Patrimonio: **${money(d.total)} 🪙**`)] }); }
    const adminCommands = ['ban','unban','kick','warn','purge','lock','unlock','slowmode','nick','addrole','removerole','mute','unmute']; if (adminCommands.includes(command) && !isAdmin(message)) return reply({ embeds: [fail('🛡️ Acceso denegado. Necesitas permisos de administrador.')] });
    if (command === 'say') { if (!isAdmin(message) || !args.length) return reply({ embeds: [fail('🛡️ Solo administradores y con texto.')] }); await message.delete().catch(() => {}); return message.channel.send({ content: args.join(' '), allowedMentions: { parse: [] } }); }
    if (command === 'warn') { const t = message.mentions.users.first(); if (!t) return reply({ embeds: [fail('❌ Usa **p.warn @usuario motivo**.')] }); getUser(t.id).warnings.push({ reason: args.slice(1).join(' ') || 'Sin motivo', by: message.author.id, at: Date.now() }); save(); return reply({ embeds: [ok(`⚠️ Advertencia registrada para ${t}.`)] }); }
    if (command === 'warns') { const t = message.mentions.users.first() || message.author, u = getUser(t.id); return reply({ embeds: [info(`⚠️ **Advertencias de ${t.username}**\n\n${u.warnings.map((w,i) => `**${i+1}.** ${w.reason}`).join('\n') || '✅ Sin advertencias.'}`)] }); }
    if (command === 'ban' || command === 'kick') { const t = message.mentions.members.first(); if (!t) return reply({ embeds: [fail(`❌ Usa **p.${command} @usuario**.`)] }); if (command === 'ban' && t.bannable) await t.ban({ reason: `Por ${message.author.tag}` }); else if (command === 'kick' && t.kickable) await t.kick(`Por ${message.author.tag}`); else return reply({ embeds: [fail('❌ No puedo realizar esa acción.')] }); return reply({ embeds: [ok(`✅ ${t.user.tag} fue ${command === 'ban' ? 'baneado' : 'expulsado'}.`)] }); }
    if (command === 'purge' || command === 'clear') { const n = Number(args[0]); if (!Number.isInteger(n) || n < 1 || n > 100) return reply({ embeds: [fail('❌ Usa una cantidad entre 1 y 100.')] }); const d = await message.channel.bulkDelete(n, true); return reply({ embeds: [ok(`🧹 Se eliminaron **${d.size} mensajes**.`)] }); }
    if (command === 'lock' || command === 'unlock') { await message.channel.permissionOverwrites.edit(message.guild.roles.everyone, { SendMessages: command === 'lock' ? false : null }); return reply({ embeds: [ok(command === 'lock' ? '🔒 Canal bloqueado.' : '🔓 Canal desbloqueado.')] }); }
    if (command === 'slowmode') { const n = Number(args[0]); if (!Number.isInteger(n) || n < 0 || n > 21600) return reply({ embeds: [fail('❌ Usa 0–21600 segundos.')] }); await message.channel.setRateLimitPerUser(n); return reply({ embeds: [ok(`🐌 Slowmode: **${n}s**`)] }); }
    if (command === 'ticket') return reply({ embeds: [embed(0x5865F2, '╭━━━〔 🎫 CENTRO DE SOPORTE 〕━━━╮', '📩 Pulsa el botón para crear un canal privado de soporte.')], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_open').setLabel('Abrir ticket').setEmoji('🎫').setStyle(ButtonStyle.Primary))] });
    if (['bienvenidas','autorroles','autorespuestas','autoreacciones'].includes(command)) return reply({ embeds: [info('🤖 Sistema de automatización disponible.')] });
    return reply({ embeds: [fail(`❓ No conozco **${PREFIX}${command}**.\n\n📚 Usa **p.help**.`)] });
  } catch (error) { console.error('❌ Error en messageCreate:', error); }
});

client.on('interactionCreate', async interaction => { try { if (interaction.isStringSelectMenu() && interaction.customId === 'joshua_help') return interaction.update({ embeds: [help(interaction.values[0])], components: [helpMenu()] }); if (!interaction.isButton() || interaction.customId !== 'ticket_open') return; const guild = interaction.guild, c = getGuildConfig(guild.id), existing = guild.channels.cache.find(ch => ch.name === `ticket-${interaction.user.id}`); if (existing) return interaction.reply({ content: `🎫 Ya tienes un ticket abierto: ${existing}`, ephemeral: true }); c.ticketCounter++; save(); const overwrites = [{ id: guild.roles.everyone.id, deny: [PermissionsBitField.Flags.ViewChannel] }, { id: interaction.user.id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages, PermissionsBitField.Flags.ReadMessageHistory] }]; if (c.ticketStaffRole) overwrites.push({ id: c.ticketStaffRole, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages, PermissionsBitField.Flags.ReadMessageHistory] }); const channel = await guild.channels.create({ name: `ticket-${interaction.user.id}`, type: ChannelType.GuildText, parent: c.ticketCategory || undefined, permissionOverwrites: overwrites, topic: `Ticket #${c.ticketCounter} • ${interaction.user.tag}` }); await channel.send({ content: `🎫 ${interaction.user} ¡tu ticket está abierto!`, embeds: [info('📩 Explica aquí tu problema. Cuando termines, usa **p.ticket close**.')], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_close').setLabel('Cerrar').setEmoji('🔒').setStyle(ButtonStyle.Danger))] }); return interaction.reply({ content: `✅ Ticket creado: ${channel}`, ephemeral: true }); } catch (e) { console.error('❌ Error en interacción:', e); if (!interaction.replied && !interaction.deferred) await interaction.reply({ content: '❌ Ocurrió un error.', ephemeral: true }).catch(() => {}); } });

client.once('ready', () => console.log(`🤖 Joshua está conectado como ${client.user.tag}`));
client.on('error', e => console.error('❌ Error de Discord:', e));
process.on('unhandledRejection', e => console.error('❌ Unhandled Rejection:', e));
process.on('uncaughtException', e => console.error('❌ Uncaught Exception:', e));
const PORT = Number(process.env.PORT) || 3000;
http.createServer((req, res) => { res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' }); res.end('Joshua está funcionando 🤖🟢'); }).listen(PORT, '0.0.0.0', () => console.log(`🌐 Servidor iniciado en el puerto ${PORT}`));
if (!process.env.DISCORD_TOKEN) { console.error('❌ Falta DISCORD_TOKEN en las variables de Render.'); process.exit(1); }
client.login(process.env.DISCORD_TOKEN).then(() => console.log('🔐 Login de Discord correcto.')).catch(e => { console.error('❌ No se pudo iniciar sesión en Discord.', e.message); process.exit(1); });
